name: bookly_clean_arch
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.6.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.6

  # Linting
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
