name: bookly_clean_arch
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  go_router: ^16.2.4
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1

  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON serialization
  json_annotation: ^4.9.0
  json_serializable: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation tools
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  retrofit_generator: ^7.0.8

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
